plugins {
    id 'java'
    id 'org.jetbrains.kotlin.jvm'
    id 'org.jetbrains.intellij.platform.module'
}

group = 'com.valb3r.bpmn.intellij.plugin.core.tests'

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

dependencies {
    intellijPlatform {
        intellijIdeaUltimate(intellijPlatformVersion)
    }

    implementation project(":xml-parser-api")
    implementation project(":bpmn-intellij-plugin-core")

    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8"

    implementation "com.fasterxml.jackson.module:jackson-module-kotlin:$jackson"

    implementation "org.junit.jupiter:junit-jupiter-api:$junitJupiter"
    implementation "org.amshove.kluent:kluent:$kluent"
    implementation "org.mockito:mockito-core:$mockitoCore"
    implementation "org.mockito.kotlin:mockito-kotlin:$mockitoKotlin"
}

sourceSets {
    main.kotlin.srcDirs += 'src/main/kotlin'
}

clean {
    delete 'out'
}
