plugins {
    id 'java'
    id 'kotlin-kapt'
    id 'org.jetbrains.kotlin.jvm'
}

group = 'com.valb3r.bpmn.intellij.plugin.bpmn.api'

java {
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

dependencies {
    api "org.jetbrains.kotlin:kotlin-stdlib"

    api "com.fasterxml.jackson.core:jackson-annotations:$jacksonAnnotations"

    api "org.mapstruct:mapstruct:$mapstruct"
    kapt "org.mapstruct:mapstruct-processor:$mapstruct"
}
