package com.valb3r.bpmn.intellij.plugin.flowable.langinjection

import com.valb3r.bpmn.intellij.plugin.commons.langinjection.DefaultDelegateExpressionUiInjector

class FlowableDelegateExpressionUiInjector: DefaultDelegateExpressionUiInjector()