package com.valb3r.bpmn.intellij.plugin.camunda.langinjection

import com.valb3r.bpmn.intellij.plugin.commons.langinjection.DefaultDelegateExpressionUiInjector

class CamundaDelegateExpressionUiInjector: DefaultDelegateExpressionUiInjector()