@startuml

skinparam ranksep 60
skinparam nodesep 60
skinparam linetype ortho

node flowable_xml_parser [
<b>flowable-xml-parser</b>
--
Provides parser, BPMN model mapping to convert
Flowable XML into dialect-agnostic format
]

node activiti_xml_parser [
<b>activiti-xml-parser</b>
--
Provides parser, BPMN model mapping to convert
Activiti XML into dialect-agnostic format
]

node xml_parser_core [
<b>xml-parser-core</b>
--
Provides core BPMN XML parsing
and update (primarily) logic
]

node xml_parser_api [
<b>xml-parser-api</b>
--
Provides dialect-agnostic DTOs
that represent BPMN model
]

node bpmn_intellij_plugin_core [
<b>bpmn-intellij-plugin-core</b>
--
Provides core rendering and element
manipulation logic
]

node flowable_intellij_plugin [
<b>flowable-intellij-plugin</b>
--
Provides final IntelliJ plugin deliverable
for Flowable-BPMN and relevant customizations
(flowable-intellij-plugin/build/distributions)
]

node activiti_intellij_plugin [
<b>activiti-intellij-plugin</b>
--
Provides final IntelliJ plugin deliverable
for Activiti-BPMN and relevant customizations
(activiti-intellij-plugin/build/distributions)
]


flowable_intellij_plugin -up-> flowable_xml_parser
flowable_intellij_plugin -up-> xml_parser_api
flowable_intellij_plugin -up-> bpmn_intellij_plugin_core
activiti_intellij_plugin -up-> activiti_xml_parser
activiti_intellij_plugin -up-> xml_parser_api
activiti_intellij_plugin -up-> bpmn_intellij_plugin_core
bpmn_intellij_plugin_core -up-> xml_parser_api
flowable_xml_parser -up-> xml_parser_core
activiti_xml_parser -up-> xml_parser_core
flowable_xml_parser --> xml_parser_api
activiti_xml_parser --> xml_parser_api

@enduml