plugins {
    id 'java'
    id 'org.jetbrains.kotlin.jvm'
    id 'org.jetbrains.intellij.platform.module'
}

group = 'com.valb3r.bpmn.intellij.plugin.commons'

java {
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

dependencies {
    intellijPlatform {
        intellijIdeaUltimate(intellijPlatformVersion)
        bundledPlugins(intellijPlatformPlugins)
    }

    implementation project(":xml-parser-api")
    implementation project(":bpmn-intellij-plugin-core")

    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8"
    implementation "com.fasterxml.jackson.module:jackson-module-kotlin:$jackson"

    // Tests
    testImplementation project(':bpmn-intellij-plugin-common-tests')
    testImplementation "org.junit.jupiter:junit-jupiter-api:$junitJupiter"
    testImplementation "org.junit.jupiter:junit-jupiter-engine:$junitJupiter"
    testImplementation "org.junit.platform:junit-platform-runner:$junitPlatformRunner"
    testImplementation "org.amshove.kluent:kluent:$kluent"
    testImplementation "org.mockito:mockito-core:$mockitoCore"
    testImplementation "org.mockito.kotlin:mockito-kotlin:$mockitoKotlin"
}

sourceSets {
    main.kotlin.srcDirs += 'src/main/kotlin'
}

clean {
    delete 'out'
}

test {
    jacoco {
        destinationFile = file("${buildDir}/jacoco/test.exec")
        includeNoLocationClasses = true
        excludes = ["jdk.internal.*"]
    }

    testLogging {
        events "failed"
        exceptionFormat = "full"
    }
}



jacocoTestReport {
    // Adjust the output of the test report
    reports {
        xml.required = true
        csv.required = true
    }
}
