name: Plugin CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: |
        ./gradlew clean build \
            :flowable-intellij-plugin:buildPlugin :flowable-intellij-plugin:verifyPlugin \
            :camunda-intellij-plugin:buildPlugin :camunda-intellij-plugin:verifyPlugin \
            :activiti-intellij-plugin:buildPlugin :activiti-intellij-plugin:verifyPlugin
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: unittests
        fail_ci_if_error: false # Observing frequent failures of code coverage uploads
