name: Plugin CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: Set up JDK 25
      uses: actions/setup-java@v5
      with:
        distribution: temurin
        java-version: 25
    - uses: gradle/actions/setup-gradle@v6
    - name: Build with Gradle
      run: |
        ./gradlew clean build \
            :flowable-intellij-plugin:buildPlugin :flowable-intellij-plugin:verifyPlugin \
            :camunda-intellij-plugin:buildPlugin :camunda-intellij-plugin:verifyPlugin \
            :activiti-intellij-plugin:buildPlugin :activiti-intellij-plugin:verifyPlugin
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: unittests
        fail_ci_if_error: false # Observing frequent failures of code coverage uploads
